ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: test.k8s.home
      paths:
        - path: /podinfo(/|$)(.*)
          pathType: ImplementationSpecific